import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '@/styles/Home.module.css'
//import Feed from './feed'
import { supabase } from './supabaseClient'

export async function getServerSideProps() {
  let { data } = await supabase.from('headlines').select('*').order('created_at', { ascending: false }).limit(250);
  return {
    props: {
     headlines: data
    },
  }
}

export default function Home({ headlines }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <main className={styles.main}>


        <div className="header">
          <div className="headerItem">
            <a href="https://github.com/aaronsdevera/Personal-News-Feed"><h3><span className="site-title">NewsFeed</span></h3></a>
          </div>
          <div className="headerItem">
            <h3><span id="insert-time" className="site-time"></span></h3>
          </div>
          <div className="headerItem">
            <h3><span id="insert-tag" className="site-tag"><input id="site-tag-input" placeholder="insert a term to highlight"></input><span id="highlight-results"></span></span></h3>
          </div>
        </div>

        <div className="feed">
            <ul>
            {headlines.map((entry) => (
                <li className="feed-item">
                  <a className="feed-item-headline" href={entry.url}>{entry.headline}</a>
                  <span className="feed-tag feed-item-sourcename">{entry.source_name}</span>
                  <span className="feed-tag feed-item-sourcetype">{entry.source_type}</span>
                  <span className="feed-tag feed-item-createdat">{entry.created_at}</span>
                </li>
            ))}
          </ul>
        </div>
      </main>
      
    </>
  )
}
