steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.10'
- run:
  - cd collections
  - pip install -r requirements.txt
  - for each in $(cat rss_sources.csv); do python3 ""
