name: poll the verge

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'
  push:
    branches:
      - main

env:
  DATA_SINK_URL: ${{ secrets.DATA_SINK_URL }}
  AUTH_HEADER_ONE_KEY: ${{ secrets.AUTH_HEADER_ONE_KEY }} 
  AUTH_HEADER_ONE_VALUE: ${{ secrets.AUTH_HEADER_ONE_VALUE }} 
  AUTH_HEADER_TWO_VALUE: ${{ secrets.AUTH_HEADER_TWO_VALUE }} 
  AUTH_HEADER_TWO_KEY: ${{ secrets.AUTH_HEADER_TWO_KEY }} 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: pip install -r collections/requirements.txt;
    - name: Poll from feed
      run: python3 collections/poll-feed.py 'The Verge' 'tech' 'https://www.theverge.com/rss/index.xml';