name: poll roll call

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

env:
  DATA_SINK_URL: ${{ secrets.DATA_SINK_URL }}
  DATA_SINK_API_KEY: ${{ secrets.DATA_SINK_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
    - run: cd collections;
    - run: pip install -r requirements.txt;
    - name: Poll from feed
      run: python3 poll-feed.py 'Roll Call' 'politics' 'https://nitter.net/rollcall/rss';