name: poll hackaday

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - main

env:
  DATA_SINK_URL: ${{ secrets.DATA_SINK_URL }}
  DATA_SINK_API_KEY: ${{ secrets.DATA_SINK_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - run: cd collections;
    - run: pip install -r requirements.txt;
    - name: Poll from feed
      run: python3 poll-feed.py 'Hackaday' 'tech' 'https://hackaday.com/blog/feed/';