name: poll the new yorker

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - main

env:
  DATA_SINK_URL: ${{ secrets.DATA_SINK_URL }}
  DATA_SINK_API_KEY: ${{ secrets.DATA_SINK_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: cd collections;
    - run: pip install -r requirements.txt;
    - name: Poll from feed
      run: python3 poll-feed.py 'The New Yorker' 'news' 'https://www.newyorker.com/feed/everything';