name: poll feeds

on:
  push:
    branches:
      - add/server-caching-model
jobs:
  poll:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - env:
      DATA_SINK_URL: ${{ secrets.DATA_SINK_URL }}
      DATA_SINK_API_KEY: ${{ secrets.DATA_SINK_API_KEY }}
    - run: cd collections; pip install -r requirements.txt; python3 poll-feed.py;
